## Mailtrap SMTP (Mail) settings for docker profile
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:shared-rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

rabbitmq.compras.events.exchange=${RABBITMQ_COMPRAS_EVENTS_EXCHANGE:peliculas.eventos.compras}
rabbitmq.compras.compra.confirmada.routing-key=${RABBITMQ_COMPRA_CONFIRMADA_ROUTING_KEY:compra.confirmada.v1}
rabbitmq.notificaciones.compra.confirmada.queue=${RABBITMQ_NOTIFICACIONES_COMPRA_CONFIRMADA_QUEUE:notificaciones.compra-confirmada.v1}
rabbitmq.notificaciones.dlx.exchange=${RABBITMQ_NOTIFICACIONES_DLX_EXCHANGE:peliculas.eventos.dlx}
rabbitmq.notificaciones.compra.confirmada.dlq=${RABBITMQ_NOTIFICACIONES_COMPRA_CONFIRMADA_DLQ:notificaciones.compra-confirmada.v1.dlq}
rabbitmq.notificaciones.compra.confirmada.dlq.routing-key=${RABBITMQ_NOTIFICACIONES_COMPRA_CONFIRMADA_DLQ_ROUTING_KEY:notificaciones.compra-confirmada.v1.dlq}
